# Generated by Django 5.2 on 2025-05-05 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songcomment',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songcomment',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='music_album_title_ddf06b_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='music_album_release_5ffcba_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['title'], name='music_playl_title_a00aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['release_date'], name='music_playl_release_a9a889_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['release_date'], name='music_song_release_8872f0_idx'),
        ),
    ]
