# Generated by Django 5.2 on 2025-05-08 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='collaborations',
            field=models.ManyToManyField(blank=True, related_name='collaborating_artists', to='music.artistcollaboration', verbose_name='Collaborations'),
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='artistcollaboration',
            name='artists',
            field=models.ManyToManyField(related_name='artist_collaborations', to='music.artist', verbose_name='Artists'),
        ),
    ]
