# Generated by Django 5.2 on 2025-05-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_collaborations_artist_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='collaborations',
        ),
        migrations.AddField(
            model_name='song',
            name='collaborations',
            field=models.ManyToManyField(blank=True, related_name='collaborating_artists', to='music.artistcollaboration', verbose_name='Collaborations'),
        ),
    ]
