# Generated by Django 5.2 on 2025-05-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_remove_artist_collaborations_song_collaborations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistcollaboration',
            name='title',
        ),
        migrations.AddField(
            model_name='artistcollaboration',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artist_collaborations', to='music.song', verbose_name='Song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='collaborations',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.artistcollaboration', verbose_name='Collaborations'),
        ),
    ]
