# Generated by Django 5.2 on 2025-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_artistcollaboration_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_playing',
            field=models.BooleanField(default=False, verbose_name='Is Playing'),
        ),
    ]
