# Generated by Django 5.2 on 2025-05-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_is_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_playing',
        ),
        migrations.DeleteModel(
            name='ListeningHistory',
        ),
    ]
