# Generated by Django 5.2 on 2025-05-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Site Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='header/%Y/%m/%d', verbose_name='Header Image')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
